sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nucoxia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nucoxia/react-test npm run test

after_success:
  - docker build -t nucoxia/multi-client ./client
  - docker build -t nucoxia/mutli-nginx ./nginx
  - docker build -t nucoxia/multi-server ./server
  - docker build -t nucoxia/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push nucoxia/multi-client
  - docker push nucoxia/multi-nginx
  - docker push nucoxia/multi-server
  - docker push nucoxia/multi-worker
